import { QuestionCategory } from "@shared/schema";

// Questions database
export const questionsData: Record<QuestionCategory, string[]> = {
  [QuestionCategory.VULNERABILITY]: [
    "What's something you're afraid to tell most people?",
    "When was the last time you felt truly seen by someone?",
    "What truth about yourself have you been avoiding?",
    "What do you wish people knew about you without you having to tell them?",
    "What's a question you're afraid to ask someone in your life?",
    "What's the most vulnerable you've ever been with someone?",
    "What's a fear you've never shared with anyone?",
    "When was the last time you felt completely understood?",
    "What are you most afraid I’ll one day realise about you?",
    "What’s something you sometimes hide from me—not because it’s big, but because it feels tender?",
    "How do you know when you’re emotionally safe with someone?",
    "What’s a moment you felt rejected by me, even if it was small?",
    "What part of you still feels like a child, especially in relationships?",
    "In what situations do you need me, but find it hard to say so?",
    "What truth about love do you wish you didn’t know?",
    "What emotion do you often feel first—but rarely name?",
    "What are you still learning to forgive yourself for?",
    "When was the last time you felt not enough, and what would you have needed in that moment?",
    "Where do you feel like we mirror each other—and where do you feel like we challenge each other?",
    "What’s something in me that awakens something dormant in you?",
    "How do I change the way you see the world?",
    "What truth about yourself do you feel more able to live when you're with me?",
    "What do you think we’re making space for in each other’s lives?",
    "What do you wish people understood about you without having to explain it?",
    "What kind of conversations make you feel closest to me?",
    "When do you feel most seen by me—and when don’t you?",
    "When do you feel most listened to—and when do you feel dismissed, even if it’s unintentional?",
    "Do you think good listening means offering input—or just being present?",
    "What does holding space for someone mean to you?",
    "What would support look like to you when you’re the one struggling?",
    "Do you ever feel guilty for needing rest or not being productive?",
    "What’s something that emotionally floors you—the kind of fear that leaves you gasping?",
    "When do you shut down and tell the world to leave you alone?",
    "When have you knowingly lied to someone you loved—and do you still stand by it?",
    "What’s one thing about me that quietly irritates you—but you usually bite your tongue about it?",
    "What do you sometimes need from me that you fear might feel like too much to ask for?",
    "Is there a part of yourself you quietly wish I’d notice—without you having to show it?",
    "When do you feel most safe to say exactly what you feel, without filtering?",
    "When do you most long for reassurance from me—but rarely ask for it?",
    "What’s a truth you hold back because you think it might weigh too heavy on me?",
    "Do you ever soften or edit your feelings for fear of changing how I see you?"
  ],
  [QuestionCategory.ATTRACTION]: [
    "What makes you feel most desired?",
    "What non-physical trait do you find most attractive in others?",
    "When do you feel most confident in your sensuality?",
    "What's something that instantly draws you to someone?",
    "What's a fantasy you've never shared?",
    "What's the most meaningful physical touch you've experienced?",
    "How do you express attraction without words?",
    "What makes you feel truly connected during intimacy?",
    "What do I do that turns you on in a subtle, unexpected way?",
    "What’s something I might not know you fantasise about?",
    "What moment between us still lingers in your body memory?",
    "Where in your body do you feel desire most strongly?",
    "What makes you feel sexy—and what kills that feeling instantly?",
    "When do you feel most wanted by me?",
    "Is there a part of your physicality you’re insecure about, but wish I adored?",
    "What kind of touch do you secretly crave more of?",
    "What words would you love to hear in bed—but rarely say aloud?",
    "What’s your favourite sensual memory of us that wasn’t explicitly sexual?",
    "When do you feel most powerful in a sexual context?",
      "What kind of attention secretly drives you wild?",
      "Have you ever seduced someone with just your words? What did you say?",
      "What’s a desire you’ve judged yourself for having?",
      "What part of your body holds the most unspoken tension?",
      "What’s something sexual you’d like to try but haven’t had the courage to bring up?",
      "Have you ever used intimacy as a way to gain control?",
      "What’s a dynamic that scares you because it turns you on?",
      "When does teasing become a form of intimacy for you?",
      "What’s a past experience you keep mentally replaying—because it still turns you on?",
      "Do you fantasise about being seen, or about staying hidden?",
      "Where does sensuality bleed into vulnerability for you?",
      "What kind of touch lingers with you for hours afterward?",
      "What’s the line between pleasure and risk in your world?",
      "What’s something that turns you on even though it ‘shouldn’t’?",
    "What scares you more: losing desire, or admitting it was never fully there?",
    "What matters more to you in the long run: how someone makes you feel, or how they look?",
    "When do you find me most irresistible—and do you wish you didn’t?",
    "Is there a part of you that’s secretly trying to seduce a part of me?",
    "What’s the most confusing part about our chemistry?",
    "Do you ever wonder whether physical attraction grows—or fades—over time?",
    "What’s the difference between being turned on and being visually captivated?",
    "Have you ever loved someone even when they didn’t match your ‘type’?",
    "What’s one way you’ve surprised yourself in how you’ve been attracted to someone?",
    "When do you feel most attractive—even if no one else says so?",
    "What’s a quality that instantly draws you to someone?",
    "What’s one way I touch you that makes you feel physically safe?",
    "Do you see yourself as attractive?",
    "Would you say you’re more dominant or more passive—in bed, and in life?",
    "What part of your personality do you secretly hope I’m falling for?",
    "What’s something about me you didn’t expect to like—but now really value?" 
  ],
  [QuestionCategory.IDENTITY]: [
    "What part of yourself do you hide from the world?",
    "When do you feel most authentically yourself?",
    "What aspect of your identity has evolved the most over time?",
    "What childhood experience shaped who you are today?",
    "What contradiction exists within your personality?",
    "What's something you believe that most people around you don't?",
    "When has your sense of self been most challenged?",
    "What part of yourself are you still discovering?",
    "Who were you before you learned to be 'good' or 'acceptable'?",
    "How has loving me changed how you see yourself?",
    "What belief about yourself is shifting right now?",
    "What part of your personality do you still not fully understand?",
    "Who do you become when you feel truly seen?",
    "What roles do you perform in daily life—and which ones exhaust you?",
    "If you weren’t afraid of losing control, how would you be different?",
    "What identity are you currently outgrowing?",
    "When do you feel most free to be 'weird' or different?",
    "What part of your soul do you protect most fiercely?",
    "What part of yourself do you feel most seen by in my presence?",
    "What part of you do I mirror back most clearly—whether you like it or not?",
    "When do you feel most you around me?",
    "Who are you when you’re not being who you think you should be?",
    "Who am I, in your eyes?",
    "What would be your commentary on my early, middle, and later life?",
    "When you’re at your happiest, what are you doing—or thinking?",
    "What brings you unbridled joy?",
    "Is your self-image closer to how you feel or how you want to be seen?",
    "If someone observed your life for a week, what would they misunderstand about you?",
    "What part of yourself do you protect most fiercely—and why?",
    "What’s a truth about yourself that only reveals itself in silence?",
    "What role do you naturally fall into in relationships—and do you want to change it?",
    "What part of your personality do you secretly hope I’m falling for?",
    "What’s something about me you didn’t expect to like—but now really value?",
    "Do you ever find yourself performing around me? If so, when—and why?",
    "What part of your personality do you secretly hope I’m falling for?",
    "What’s something about me you didn’t expect to like—but now really value?",
    "Do you ever find yourself performing around me? If so, when—and why?"
  ],
  [QuestionCategory.CONFLICT]: [
    "How do you typically respond when someone hurts you?",
    "What's your pattern in conflict that you wish you could change?",
    "What's the hardest apology you've ever had to make?",
    "What boundaries do you struggle to maintain with others?",
    "When was a time someone misunderstood your intentions?",
    "What's something you need in conflict that you rarely get?",
    "What's a conflict you've never fully resolved?",
    "How has your approach to disagreements changed over time?",
    "What’s a way I unintentionally hurt you—but you weren’t sure how to bring it up?",
    "When you feel distant from me, what do you need most—and what do you usually do instead?",
    "How do you tend to protect yourself when you feel emotionally threatened?",
    "What’s one thing you’ve forgiven me for, even if I don’t know it?",
    "What kind of tone or energy makes you feel most defensive?",
    "When we argue, what do you fear it means about us?",
    "What does 'making up' look or feel like for you?",
    "When do you feel like you’re walking on eggshells with me?",
    "What apology would mean the most to you—what words do you wish I’d say?",
    "How do you know when something between us is truly healed?",
    "If we were characters in a novel, what would the tension between us be about?",
    "Are we agreeing too often—and if so, is that stifling something important between us?",
    "Is agreement in a relationship a form of safety—or a subtle threat to growth?",
    "What’s one low-level annoying habit of mine you’d secretly like me to change?",
    "List five things that make you really annoying to live with.",
    "Do we give each other enough friction, or are we too polite?",
    "How do you feel things should be made right after a disappointment?",
    "After a conflict or disappointment, do you tend to feel misunderstood, abandoned, let down—or judged? Why?",
    "In a fight, do you ever cling to being right—even if it means shooting yourself in the foot?",
    "What’s one thing I could do that would make you feel more secure during conflict?",
    "When I withdraw emotionally, how does it land for you—and what do you tell yourself about it?",
    "What is harder for you in arguments: letting go of your point, or letting go of your hurt?",
    "Is there something about how I express frustration that you find hard to handle?",
    "Do you trust that we can fully repair after conflict—or do small traces sometimes stay?"
  ],
  [QuestionCategory.FUTURE]: [
    "If you could guarantee one thing in your future, what would it be?",
    "What dream seems impossible but you still hope for?",
    "How do you imagine your life in 20 years?",
    "What future milestone are you most looking forward to?",
    "What legacy do you hope to leave?",
    "What future technology both excites and scares you?",
    "What part of the future makes you most anxious?",
    "If you could send a message to your future self, what would it say?",
    "If we lived together for a year, what rituals or routines do you imagine we’d create?",
    "What kind of adventure would stretch us both—but bring us closer?",
    "What’s one area of life you secretly hope I’ll pull you into?",
    "Imagine a version of us five years from now. What feels magnetic about that version?",
    "If we built a home together, what would it absolutely have to include?",
    "What role would you want to grow into more with me?",
    "What does thriving look like for you—and how could we support that for each other?",
    "What’s something we haven’t explored yet that you want to explore?",
    "What would a beautiful letting go look like between us, if our paths diverged one day?",
    "What does freedom mean to you in a long-term connection?",
    "Do you think we met at the wrong time, or the only time it could’ve worked?",
    "If you lost your job tomorrow, what would you do—and on what timescale?",
    "12 months from now: where are you, what are you doing, and are you happier?",
    "What are your expectations around love, health, and career in the next five years?",
    "If your life had a theme song this year, what would it be—and why?",
    "What are you secretly hoping changes in the next 12 months?"
  ],
  [QuestionCategory.SHADOW]: [
    "What quality in others triggers jealousy in you?",
    "What part of yourself do you judge most harshly?",
    "What do you envy about someone close to you?",
    "When have you acted in a way that contradicted your values?",
    "What thought have you had that you'd be ashamed to share?",
    "What makes you feel insecure in relationships?",
    "What's something you've done that you hope people never find out about?",
    "What part of yourself do you try to improve but struggle with?",
    "What part of yourself do you worry is 'too much' for me?",
    "When have you felt a pang of jealousy or comparison—even if you didn’t say it?",
    "What do you sometimes project onto me that’s really about your past?",
    "When do you fear being abandoned—even subtly?",
    "What part of me feels hardest for you to fully trust?",
    "What would you never want me to see in you?",
    "In what moments do you start building a story in your head about me—and what do those stories sound like?",
    "When do you feel most not enough in this connection?",
    "What are you afraid I’ll one day leave you for?",
    "What dark or messy feeling do you wish I could hold without needing to fix it?",
    "What do you think we’re healing together, without even trying?",
    "What do you think my soul is learning through knowing you?",
    "What do you think you’re waking up in me?",
    "Where do you feel the most resistance with me—and what might that be inviting you to heal?",
    "Is there something in me that challenges a part of you you’re still figuring out?",
    "What do you think we’re unlearning together?",
    "Do you fear the security your job gives you?",
    "What parts of you are still under construction?",
    "What’s something you’ve outgrown but still haven’t fully let go of?",
    "What question do you find yourself returning to again and again in life?",
    "What are you secretly trying to prove, and to whom?",
    "What’s something you sense in me that I don’t yet fully see or own?",
    "In relationships, who do you compare yourself to—and what do you see in them that you don’t yet own in yourself?",
    "When have you second-guessed a partner—and what was really going on underneath?",
    "What are you secretly a little jealous of in me?"
  ],
  [QuestionCategory.SURPRISE]: [
    "What's the most spontaneous decision you've ever made?",
    "What belief have you completely reversed in your life?",
    "What's the most out-of-character thing you've ever done?",
    "What secret talent or skill do you have that surprises people?",
    "What's something that happened to you that seems unbelievable?",
    "What dream or goal have you never told anyone about?",
    "What's a coincidence that happened to you that seemed almost magical?",
    "What's a random fact about you that most people wouldn't guess?",
    "If I weren’t me—who do you imagine I’d be?",
    "What’s something you’ve never told anyone, not because it’s shameful—but because it felt too precious?",
    "If this moment had a soundtrack, what would it be?",
    "What do you think I don’t see about you—but you wish I did?",
    "If a poet were watching us right now, what line would they write?",
    "What question would scare you most if I asked it right now?",
    "What feels surprisingly easy between us that you thought would be hard?",
    "What kind of magic do you think we accidentally create together?",
    "What’s one totally batshit crazy thing you would love to do right now—and what’s stopping you?",
    "You wake up and every responsibility is gone. What do you do with today?",
    "Without thinking—what’s the first word or image that comes to mind when you hear: Greece, Potato, Clock, Me, Coffee?",
    "If you could have one new inanimate object right now—what would it be? (Lotti and Pimpa don’t count!)",
    "If we could each rewrite one moment between us so far, what would you choose?",
    "What’s something we haven’t done yet that you secretly hope will happen between us?",
    "Describe me as if you were a poet—not a partner.",
    "If you could hit a ‘pause button’ on us right now—just to savour this phase—would you? Why or why not?"
  ],
  [QuestionCategory.DEATH]: [
    "What would you want your last words to be?",
    "What do you hope people remember about you after you're gone?",
    "What relationship do you most regret not healing?",
    "What gives you comfort when thinking about mortality?",
    "What would you do differently if you knew you had one year left?",
    "What part of yourself have you had to let go of as you've grown?",
    "What loss has taught you the most?",
    "What do you hope exists after death?",
    "If I died unexpectedly, what would you wish you’d said to me?",
    "What do you hope I never forget about you—even if we part ways one day?",
    "How do you want to be remembered—not generally, but by me?",
    "What’s one small moment of ours you’d put in a time capsule?",
    "What would you want us to do together if we had one last day?",
    "What do you imagine you’d keep doing just because it reminds you of me?",
    "What would a loving goodbye look like between us?",
    "What helps you feel close to those who are no longer here?",
    "Are you scared of being alone for the rest of your life?",
    "If you were to leave behind one message for the world, what would it be—one sentence only?"
  ],
  [QuestionCategory.UNSPOKEN]: [
    "What's a thought you've had recently that you haven't told anyone?",
    "What conversation are you avoiding having?",
    "What question do you wish someone would ask you?",
    "What do you wish you could say to someone but can't?",
    "What's something you've never found the right words to express?",
    "What's a silent understanding you have with someone?",
    "What do you think people assume about you that isn't true?",
    "What's something meaningful you've never told someone who deserves to hear it?",
    "What’s something you feel between us—but haven’t had words for?",
    "When have I misread you completely—and you didn’t correct me?",
    "What emotion do you often withhold from me, and why?",
    "What do you sense I’m holding back—but wish I’d name?",
    "When do you know I’m not saying the full truth—even if I’m smiling?",
    "What are you most afraid would change if you said exactly what you feel?",
    "What do you long for me to intuitively understand—without you having to ask?",
    "What part of you is quietly watching this connection, evaluating or wondering?",
    "What truth do you feel safest telling me—but still hesitate to?",
    "What are we teaching each other without words?",
    "Do you ever feel like we’re meeting in a place beneath words?",
    "What’s one thought you’ve had about me that you weren’t sure you should say out loud?",
    "What’s your emotional safe word when things get too real?",
    "What’s something you’d never dare to ask me… but really want to?",
    "If this were a game of truth or dare, what would you not want me to pick?",
    "In what ways am I (at times) annoying or a bit useless?",
    "In what ways am I (at times) simply delightful?",
    "List three people who currently drive you mad—but you have to tolerate them. (I don’t count!)",
     "When do you feel most supported by me—and when do you feel most crowded by me?",
      "What does ‘space’ look like to you when you most need it? And how can I recognise that moment?",
      "When you want to protect your energy, what is the best way for me to stay connected to you without adding pressure?",
      "What’s one thing I do when I think I’m helping—but it might not land as helpful for you?",
      "How can I tell the difference between when you need reassurance, and when you need me to simply back off?",
      "When you’re close to your emotional limits, what do you most wish I would remember about you?",
      "What’s one sentence you would love to hear from me when you’re feeling drained or emotionally fragile?"
  ],
  [QuestionCategory.SYMBOLS]: [
    "What symbol or image has always resonated with you?",
    "What recurring dream or theme appears in your life?",
    "What object holds the most emotional significance to you?",
    "What metaphor best describes how you move through life?",
    "What animal do you feel a connection with and why?",
    "What element (earth, air, fire, water) do you most identify with?",
    "What story or myth has most influenced your worldview?",
    "What symbol represents a turning point in your life?",
    "If my presence were a symbol or image, what would it be?",
    "What colour, texture, or temperature does our connection have right now?",
    "What’s your soul teaching mine?",
    "What does my energy feel like when I’m not in the room?",
    "What inner animal or guide shows up for you when you think about this relationship?",
    "If you had to draw a map of how our souls are connected, what would it look like?",
    "What role do we play in each other’s story that goes beyond romance or logic?",
    "What kind of medicine do I bring into your life?",
    "If our connection was a poem, what would its last line be?",
    "In what ways do you think our meeting was meant to happen?",
    "If our connection were a message from the universe, what would it be saying?",
    "If we were part of each other’s karmic curriculum, what lesson might I be for you?",
    "What feels ancient about this bond?",
    "What emotion do you think your soul recognises in mine?",
    "If this connection were a sentence, what would it say?",
    "Is there something between us that feels like it existed before we had language for it?",
    "If our connection were a song, would it be more slow burn, dirty beat, or dramatic ballad?",
    "What would the ‘deleted scene’ be in our story so far?",
    "When you look at the stars, what do you think about?",
    "Pick one—mountains or ocean—and tell me why.",
    "Tell me about one piece of art you adore more than any other—song, image, poem, anything.",
    "What do you think our connection is preparing us for—even if we can’t name it yet?",
    "If this were the very last conversation we’d ever have—what would you want to make sure you said?",
    "What does being fully ‘met’ by someone mean to you—and do you feel it with me?",
    "What part of my energy do you think your soul keeps trying to understand?",
    "Where do you think I still protect myself too much around you?"
  ],
  [QuestionCategory.HOME]: [
    "Where or with whom do you feel most at home?",
    "What ritual makes you feel connected to your roots?",
    "What does 'coming home' mean to you beyond a physical place?",
    "What part of your heritage or culture feels most meaningful?",
    "What scent or sound instantly brings you comfort?",
    "What tradition do you hope to pass on?",
    "When have you felt homesick for something that wasn't a place?",
    "What makes a space feel sacred to you?",
    "When have you felt most safe with me—body, heart, and soul?",
    "What’s something small I do that makes you feel deeply known?",
    "What do you never have to pretend around me?",
    "What would 'home' feel like in our connection, if you described it without words?",
    "What calms you down when you’re with me, even if you're agitated?",
    "What do you love about how we come back to each other?",
    "What part of you feels like it belongs here?",
    "What would staying look like—not just physically, but emotionally?",
    "What’s one small thing I do that makes you feel loved without words?",
    "Where do you feel safest with me—physically, emotionally, or otherwise?",
    "What kind of silence between us feels most meaningful?",
    "What kind of silence feels supportive to you?",
    "How do you know when someone is emotionally available for you?",
    "When do you feel most free to just let go and not manage things?"
  ],
  [QuestionCategory.CROSSROADS]: [
    "What decision changed the course of your life?",
    "What path not taken do you still wonder about?",
    "What choice are you currently facing?",
    "When have you chosen safety over risk and regretted it?",
    "When have you chosen risk over safety and been grateful?",
    "What's the hardest decision you've ever had to make?",
    "What life chapter feels like it's ending or beginning right now?",
    "What's a crossroads you can see coming in your future?",
    "What choice are you currently holding back from making—and why?",
    "When do you feel torn between two versions of yourself?",
    "What crossroads are we approaching that neither of us has named yet?",
    "What would change if you stopped trying to control the outcome?",
    "What decision in our connection felt small but changed something big?",
    "What do you need in order to make a brave choice?",
    "What’s a decision you regret not making?",
    "What would choosing each other more fully look like—not in theory, but practically?",
    "Are we constrained by the stories we’ve told ourselves about our past?",
    "Do you feel your job offers freedom, or is it a trap in disguise?",
    "What’s one thing in your life that feels like a cage, even if it’s beautiful?",
    "What does shared responsibility look like to you in love?",
    "If this (relationship/career/city) vanished tomorrow—what would you try instead?"
  ]
};

// Pastel color palette for category tiles
export const categoryColors = {
  [QuestionCategory.VULNERABILITY]: "bg-red-200",
  [QuestionCategory.ATTRACTION]: "bg-pink-200",
  [QuestionCategory.IDENTITY]: "bg-purple-200",
  [QuestionCategory.CONFLICT]: "bg-orange-200",
  [QuestionCategory.FUTURE]: "bg-blue-200",
  [QuestionCategory.SHADOW]: "bg-slate-200",
  [QuestionCategory.SURPRISE]: "bg-lime-200",
  [QuestionCategory.DEATH]: "bg-gray-200",
  [QuestionCategory.UNSPOKEN]: "bg-violet-200",
  [QuestionCategory.SYMBOLS]: "bg-amber-200",
  [QuestionCategory.HOME]: "bg-green-200",
  [QuestionCategory.CROSSROADS]: "bg-teal-200"
};

// Darker versions for borders
export const borderColors = {
  [QuestionCategory.VULNERABILITY]: "border-red-300",
  [QuestionCategory.ATTRACTION]: "border-pink-300",
  [QuestionCategory.IDENTITY]: "border-purple-300",
  [QuestionCategory.CONFLICT]: "border-orange-300",
  [QuestionCategory.FUTURE]: "border-blue-300",
  [QuestionCategory.SHADOW]: "border-slate-300",
  [QuestionCategory.SURPRISE]: "border-lime-300",
  [QuestionCategory.DEATH]: "border-gray-300",
  [QuestionCategory.UNSPOKEN]: "border-violet-300",
  [QuestionCategory.SYMBOLS]: "border-amber-300",
  [QuestionCategory.HOME]: "border-green-300",
  [QuestionCategory.CROSSROADS]: "border-teal-300"
};

// Hover effects for buttons
export const hoverButtonColors = {
  [QuestionCategory.VULNERABILITY]: "hover:bg-red-400",
  [QuestionCategory.ATTRACTION]: "hover:bg-pink-400",
  [QuestionCategory.IDENTITY]: "hover:bg-purple-400",
  [QuestionCategory.CONFLICT]: "hover:bg-orange-400",
  [QuestionCategory.FUTURE]: "hover:bg-blue-400",
  [QuestionCategory.SHADOW]: "hover:bg-slate-400",
  [QuestionCategory.SURPRISE]: "hover:bg-emerald-400",
  [QuestionCategory.DEATH]: "hover:bg-gray-400",
  [QuestionCategory.UNSPOKEN]: "hover:bg-violet-400",
  [QuestionCategory.SYMBOLS]: "hover:bg-amber-400",
  [QuestionCategory.HOME]: "hover:bg-green-400",
  [QuestionCategory.CROSSROADS]: "hover:bg-indigo-400"
};

// Button colors
export const buttonColors = {
  [QuestionCategory.VULNERABILITY]: "bg-red-300",
  [QuestionCategory.ATTRACTION]: "bg-pink-300",
  [QuestionCategory.IDENTITY]: "bg-purple-300",
  [QuestionCategory.CONFLICT]: "bg-orange-300",
  [QuestionCategory.FUTURE]: "bg-blue-300",
  [QuestionCategory.SHADOW]: "bg-slate-300",
  [QuestionCategory.SURPRISE]: "bg-emerald-300",
  [QuestionCategory.DEATH]: "bg-gray-300",
  [QuestionCategory.UNSPOKEN]: "bg-violet-300",
  [QuestionCategory.SYMBOLS]: "bg-amber-300",
  [QuestionCategory.HOME]: "bg-green-300",
  [QuestionCategory.CROSSROADS]: "bg-indigo-300"
};

// Focus ring colors
export const focusButtonColors = {
  [QuestionCategory.VULNERABILITY]: "focus:ring-red-300",
  [QuestionCategory.ATTRACTION]: "focus:ring-pink-300",
  [QuestionCategory.IDENTITY]: "focus:ring-purple-300",
  [QuestionCategory.CONFLICT]: "focus:ring-orange-300",
  [QuestionCategory.FUTURE]: "focus:ring-blue-300",
  [QuestionCategory.SHADOW]: "focus:ring-slate-300",
  [QuestionCategory.SURPRISE]: "focus:ring-emerald-300",
  [QuestionCategory.DEATH]: "focus:ring-gray-300",
  [QuestionCategory.UNSPOKEN]: "focus:ring-violet-300",
  [QuestionCategory.SYMBOLS]: "focus:ring-amber-300",
  [QuestionCategory.HOME]: "focus:ring-green-300",
  [QuestionCategory.CROSSROADS]: "focus:ring-indigo-300"
};

// Category icons (using Lucide React icon names)
export const categoryIcons = {
  [QuestionCategory.VULNERABILITY]: "Heart",
  [QuestionCategory.ATTRACTION]: "Flame",
  [QuestionCategory.IDENTITY]: "User",
  [QuestionCategory.CONFLICT]: "ShieldAlert",
  [QuestionCategory.FUTURE]: "Rocket",
  [QuestionCategory.SHADOW]: "Moon",
  [QuestionCategory.SURPRISE]: "Sparkles",
  [QuestionCategory.DEATH]: "Leaf",
  [QuestionCategory.UNSPOKEN]: "MessageSquare",
  [QuestionCategory.SYMBOLS]: "Compass",
  [QuestionCategory.HOME]: "Home",
  [QuestionCategory.CROSSROADS]: "GitFork"
};
