// Wildcard prompts - special interactive prompts for deeper connection
export const wildcardPrompts = [
  "Close your eyes. Speak the first word that rises in your chest. Then explain it.",
  "Name a truth you're currently resisting — and let it be heard without trying to fix it.",
  "Say a goodbye to something you no longer need — even if it's abstract.",
  "Share a memory that feels sacred to you, even if it's small or strange.",
  "Whisper a wish for the other person's soul — something you've never said aloud.",
  "Where in your body do you feel our connection right now? Place your hand there.",
  "Take turns describing the other's energy today — using only metaphors.",
  "Look at each other in silence for 30 seconds. Then say the thing that scares you most about this closeness.",
  "Trace an outline of your connection using your finger in the air — explain what the shape means.",
  "Name a place on your body that feels open — and one that feels closed.",
  "Without speaking, act out a feeling you've had about this relationship recently. Let the other guess.",
  "Choose an object nearby that reflects how you see yourself in this relationship — explain.",
  "Imagine your connection as a weather pattern — describe the forecast.",
  "Describe each other as if you were characters in a novel — what role are you playing right now?",
  "Say something beautiful about the other person in the most awkward way possible.",
  "Share a recurring image, dream, or symbol that's been showing up in your life — and what you think it wants to tell you.",
  "Choose an archetype (e.g. the Seeker, the Guardian, the Mirror) — which one are you being for each other today?",
  "Pull a 'card': close your eyes and speak a message you imagine your future self sending to this moment.",
  "Whisper something as if the other person were about to fall asleep. Say it like a spell or blessing.",
  "Name a part of your inner world you've never shown anyone — and describe it like a room.",
  "Swap phones for 5 minutes. No deleting allowed.",
  "Tell the other person something you’ve never said out loud.",
  "Make up a story that includes the words: fire, kiss, and secret.",
  "Ask me a question you think I’ll refuse to answer.",
  "Both of you close your eyes for a full minute holding hands. What did you feel?",
  "Exchange playlists and pick one song for the other to explain.",
  "Choose one thing the other person has to do tomorrow. Be kind but bold.",
  "Take a photo together right now, no matter what mood you’re in.",
  "Pick a random object in the room and make up a shared memory about it.",
  "Whisper something to me that would be inappropriate in a work meeting.",
  "Swap seats and argue the opposite perspective of the last disagreement you had.",
  "Each share one small habit the other does that you secretly find a bit annoying.",
  "Imagine you're writing each other’s biographies—how would you title the current chapter of the other’s life?",
  "Say one thing you sometimes pretend not to care about, but actually do.",
  "Take turns describing each other’s ideal lives in one year—without asking first.",
  "Say something you think but rarely dare to say out loud.",
  "For the next 3 minutes, one person talks, the other only listens—no comments allowed.",
  "Ask the other person: ‘How are you, really?’ and don’t interrupt the answer.",
  "For the next 60 seconds, one person talks about anything they want — the other just listens without reacting. Then switch.",
  "Without explaining, name one thing about me you find utterly irresistible.",
  "Name one situation where you don’t trust me fully — and one where you trust me completely.",
  "Each write down one question you’d love to ask but are scared to. Then swap and answer.",
  "Say something you believe about us that you’ve never said out loud.",
  "Describe, in three words, how you think I see you when you’re most vulnerable.",
  "Choose one moment we’ve shared that you secretly replay sometimes — then tell me.",
  "If you could ask for one change in how we relate, what would it be?",
  "Look at me for one full minute. At the end, say the first sentence that comes to mind.",
  "Finish this sentence about me: ‘You probably don’t realise it, but you...’",
  "For the next minute, communicate only with your eyes. No words, no touch.",
  "Each of us rewrite the ending of our last disagreement or difficult moment — out loud, in one sentence.",
  "Each write down on your phone, right now, what you feel in this moment about us. Then read it to each other.",
  "Write a one-line confession to the other person — something you haven’t voiced before. Exchange and read.",
  "If you had to send me a message that you don’t dare to send, what would it say?",
  "Without thinking too hard: Where are we, 3 years from now — paint the scene in one paragraph.",
  "Close your eyes. The other person says one thing they deeply appreciate about you.",
  "Say the first sentence that comes to mind when you hear: Fire. Mirror. Home. Distance."
  ];